# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1263649ff198679c47e5b946f813674e"
name = "Xtal Search"
handle = "xtal-search-1"
application_url = "https://hotels-surfing-ss-und.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xteal-sandbox-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/product/delete"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/product/new"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/product/update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://hotels-surfing-ss-und.trycloudflare.com/auth/callback",
  "https://hotels-surfing-ss-und.trycloudflare.com/auth/shopify/callback",
  "https://hotels-surfing-ss-und.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
