# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1263649ff198679c47e5b946f813674e"
application_url = "https://example.com/"
embedded = true
name = "Xtal Search"
handle = "xtal-search-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
